name: reviewdog
on: [pull_request]
jobs:
  shfmt:
    name: runner / shfmt
    runs-on: ubuntu-latest
    permissions:
      contents: read|write
      pull-requests: read|write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run shfmt
        uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ github.token }}
          level: error
          reviewdog_flags: -reporter github-pr-review
