name: shfmt
on: [pull_request]
jobs:
  shfmt:
    name: runner / shfmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run shfmt
        uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          reviewdog_flags: -reporter github-pr-review
